- name: Install ikev2 packages
  ansible.builtin.apt:
    pkg:
      - strongswan
      - strongswan-pki
      - libcharon-extra-plugins
      - libcharon-extauth-plugins
      - libstrongswan-extra-plugins
      - libtss2-tcti-tabrmd0
    update_cache: yes

- name: Copy pki dir
  ansible.builtin.copy:
    src: ../files/ipsec.d
    dest: /etc/


- name: Copy other config files
  ansible.builtin.copy:
    src: ../files/{{ item }}
    dest: /etc/
  loop:
    - ipsec.conf.j2
    - ipsec.secrets

- name: Restart service
  ansible.builtin.systemd:
    state: restarted
    name: strongswan-starter

