- name: Create build directory
  file: 
    path: /home/{{ ansible_user }}/nginx-docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Dockerfile
  copy:
    src: ../files/Dockerfile
    owner: root
    group: root
    mode: '0644'

- name: Build container
  community.docker.docker_image:
    name: vsfi_nginx:v1.0
    build:
      path: /home/{{ ansible_user }}/nginx-docker
      source: build
    state: present

- name: Run Nginx container
  community.docker.docker_container:
    name: nginx
    image: vsfi_nginx:v1.0