- name: Create build directory
  ansible.builtin.file:
    path: ~/nginx-docker
    state: directory
    mode: '0755'

- name: Copy directory with nginx
  ansible.builtin.copy:
    src: ../files
    dest: ~/nginx-docker/

- name: Build container
  community.docker.docker_image:
    name: vsfi_nginx:v1.0
    build:
      path: ~/nginx-docker/files/
    source: build
    state: present

- name: Run Nginx container
  community.docker.docker_container:
    name: nginx
    ports:
      - 80:80
    image: vsfi_nginx:v1.0

