route:
  receiver: 'bogdan'

receivers:
  - name: 'bogdan'
    telegram_configs:
    - send_resolved: true
      api_url: https://api.telegram.org
      bot_token: ${TOKEN}
      chat_id: ${CHAT_ID}
      parse_mode: HTML


