version: "3.9"
services:
  nginx:
    build:
      context: ../nginx-docker/files/
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - /pki/private/wiki-key.key:/etc/ssl/certs/wiki-key.key:ro
      - /pki/certs/wiki-cert.cert:/etc/ssl/certs/wiki-cert.cert:ro
    ports:
      - '80:80'
      - '443:443'

  wiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Russia/Samara
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - '8080-8083:80'
    scale: 4
    restart: unless-stopped
