global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["server2.patchka.vsfi:9090"]

  - job_name: "server1"
    static_configs:
    - targets: ["server1.patchka.vsfi:9100"]
  - job_name: "server2"
    static_configs:
    - targets: ["server2.patchka.vsfi:9100"]
