- name: Copy ssh private_key
  ansible.builtin.copy:
    src: ../files/vsfi.key
    dest: ~/.ssh/
    mode: '0600'

- name: Copy generate script to server
  ansible.builtin.copy:
    src: ../files/generate-cert.sh
    dest: ~/.
    mode: '0700'
    
- name: Run generate script
  ansible.builtin.shell:
    cmd: ./generate-cert.sh {{ item }}
  loop:
    - web
    - wiki
    - prometheus
    - grafana
  