- name: Install bind9
  ansible.builtin.apt:
    pkg:
      - bind9
      - bind9utils 
      - bind9-doc
    state: latest
    update_cache: true

- name: Copy named.conf
  ansible.builtin.copy:
    src: /home/nocturnalq/vsfi2022/roles/bind9/files/etc_bind/named.conf
    dest: /etc/bind/named.conf

- name: Copy named.conf.options
  ansible.builtin.copy:
    src: /home/nocturnalq/vsfi2022/roles/bind9/files/etc_bind/named.conf.options
    dest: /etc/bind/named.conf.options

- name: Copy named.conf.local
  ansible.builtin.copy:
    src: /home/nocturnalq/vsfi2022/roles/bind9/files/etc_bind/named.conf.local
    dest: /etc/bind/named.conf.local

- name: Copy zones
  ansible.builtin.copy:
    src: /home/nocturnalq/vsfi2022/roles/bind9/files/etc_bind/zones
    dest: /etc/bind/

- name: Check conf
  ansible.builtin.shell:
    cmd: sudo named-checkconf

- name: Restart bind9
  ansible.builtin.systemd:
    state: restarted
    name: bind9