- name: Mkdir for bind9
  ansible.builtin.file:
    path: ~/bind9
    state: directory

- name: Copy Dockerfile
  ansible.builtin.copy:
    src: ../files/Dockerfile
    dest: ~/bind9/
    owner: root
    group: root
    mode: '0644'

- name: Build Bind9 container
  community.docker.docker_image:
    name: vsfi_bind9:v1.0
    build:
      path: ~/bind9/Dockerfile
      source: build
    state: present

- name: Rund Bind9 container
  community.docker.docker_container:
    name: bind9
    image: vsfi_bind:v1.0