version: '3.6'
services:
  web:
    image: 'registry.vsfi.org/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - './gitlab_volume/config:/etc/gitlab'
      - './gitlab_volume/logs:/var/log/gitlab'
      - './gitlab_volume/data:/var/opt/gitlab'
    shm_size: '256m'