- name: Install ufw
  ansible.builtin.apt:
    pkg:
      - ufw
    update_cache: true

- name: Update ufw rules for services
  community.general.ufw:
    rule: allow
    name: '{{ item }}'
  loop:
    - OpenSSH
    - Bind9

- name: Update ufw rules for ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - '500'
    - '4500'
    - '80'
    - '443'

- name: Copyt ikev2 configs
  ansible.builtin.copy:
    src: ../files/{{ item }}
    dest: /etc/ufw/
  loop:
    - sysctl.conf
    - before.rules

- name: Copy ufw config
  ansible.builtin.copy:
    src: ../files/{{ item }}
    dest: /etc/default/
  loop:
    - ufw

- name: Deny other ports
  community.general.ufw:
    default: deny

- name: Restart ufw
  community.general.ufw:
    state: enabled
    policy: allow