global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["192.168.0.157:9090"]

  - job_name: "miron_pc"
    static_configs:
    - targets: ["192.168.0.157:9101"]
  - job_name: "192.168.88.34"
    static_configs:
    - targets: ["192.168.88.34:9101"]
