- name: Create nginx dir
  ansible.builtin.file:
    path: ~/nginx-docker
    state: directory
    mode: '0755'

- name: Copy directory with nginx
  ansible.builtin.copy:
    src: ../../nginx/files
    dest: ~/nginx-docker/

- name: Create webservices dir
  ansible.builtin.file:
    path: ~/webservices
    state: directory
    mode: '0755'

- name: Create monitoring dir
  ansible.builtin.file:
    path: ~/monitoring
    state: directory
    mode: '0755'

- name: Copy files
  ansible.builtin.copy:
    src: ../files/{{ item }}
    dest: ~/monitoring
  loop:
    - prometheus.yml

- name: Create grafana dir
  ansible.builtin.file:
    path: ~/grafana
    state: directory
    mode: '0755'

- name: Copy files to grafana dir
  ansible.builtin.copy:
    src: ../files/{{ item }}
    dest: ~/grafana
  loop:
    - alerting
    - plugins 
    - config.monitoring

- name: Copy webservices compose
  ansible.builtin.copy:
    src: ../files/docker-compose.yml
    dest: ~/webservices/

# - name: Delete webserver and grafana
#   ansible.builtin.shell:
#     cmd: ./docker-rm.sh

- name: Run docker-compose
  community.docker.docker_compose:
    project_src: ~/webservices
    build: yes


