- name: Install all dependecies
  ansible.builtin.apt:
    name: "{{ list_of_packages }}"
    state: present
    update_cache: yes

- name: Add Docker GPG apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce 
  ansible.builtin.apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Install Docker and Docker-compose Modules for python
  ansible.builtin.pip:
    name: "{{ pip_packages }}"

- name: Install docker-compose 
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'

- name: Add user to group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reload rights for Docker group
  ansible.builtin.shell:
    cmd: su - $USER