- name: Install all dependecies
  ansible.builtin.yum:
    name: "{{ list_of_packages }}"
    state: present
    update_cache: yes

- name: Add Docker GPG apt key
  ansible.builtin.rpm_key:
    url: https://download.docker.com/linux/rhel/gpg
    state: present

- name: Add repository into repo.d list
  ansible.builtin.yum_repository:
      name: docker
      description: docker repository
      baseurl: "https://download.docker.com/linux/rhel/$releasever/$basearch/stable"
      enabled: true
      gpgcheck: true
      gpgkey: "https://download.docker.com/linux/rhel/gpg"

- name: Install Docker and Docker-compose Modules for python
  ansible.builtin.pip:
    name: "{{ pip_packages }}"

- name: Install docker-compose 
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'

- name: Add user to group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Reload rights for Docker group
  ansible.builtin.shell:
    cmd: su - $USER