global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # Alertmanager's default port is 9093
        - server2.patchka.vsfi:9093

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["server2.patchka.vsfi:9090"]

  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
    - targets: 
        - server1.patchka.vsfi:9100 
        - server2.patchka.vsfi:9100


